name: Deploy Firebase Config

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Szeretetben App main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "REACT_APP_FIREBASE_APIKEY=${{ secrets.FIREBASE_APIKEY }}" >> .env
          echo "REACT_APP_FIREBASE_APPID=${{ secrets.FIREBASE_APPID }}" >> .env
          echo "REACT_APP_FIREBASE_MEASUREMENTID=${{ secrets.FIREBASE_MEASUREMENTID }}" >> .env
          echo "REACT_APP_FIREBASE_SENDERID=${{ secrets.FIREBASE_SENDERID }}" >> .env

      - name: Deploy application
        run: npm run build
